version: '2'
services:
  db:
    image: postgres:9.5

  web:
    build: .
    command: bundle exec rails s -b 0.0.0.0
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - ../analytics-data/:/analytics-data
      - .:/art-analytics

  graphql:
    build:
      context: .
      dockerfile: Dockerfile.graphql
    command: postgraphql -c postgres://postgres@db:5432/art_analytics_development -w --host 0.0.0.0
    ports:
      - "5000:5000"
    links:
      - db
