default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  user: postgres
  pool: 5
  port: 5432
  host: <%= ENV['DB_HOST'] || 'db' %>

development:
  <<: *default
  database: art_analytics_development

test:
  <<: *default
  database: art_analytics_test

production:
  <<: *default
  database: art_analytics_production
  username: art-analytics
  password: <%= ENV['ART-ANALYTICS_DATABASE_PASSWORD'] %>
